### ISSUE TITLE
Templates break Updatebot

### ISSUE THREAD

**Issue by Krullenbol** [nozel-org/freebsd-updatebot#1]
Updatebot tries not only to update existing jails, but also templates. Since a template can't be run, Updatebot gets stuck and then doesn’t complete updating other jails well.
Suggested solution: exclude templates from being updated.
If updating a template is desired, the template should be converted to a regular jail first (iocage set template=no $jailname).

**Comment by sveeke** [comment]
Fixed in https://github.com/nozel-org/freebsd-updatebot/commit/65ebc41f0476dfe5c2fae99484ab0f763fbc2e18. Was a issue with `iocage` behavior so now `iocage`'s logic has been cut out.
